_BASE_: ../Base-YouTubeVIS-VideoInstanceSegmentation.yaml

MODEL:
  META_ARCHITECTURE: "DVIS_online_rfdetr"
  SEM_SEG_HEAD:
    NUM_CLASSES: 40
  MASK_FORMER:
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 200
    NHEADS: 8
    DIM_FEEDFORWARD: 2048
    DEC_LAYERS: 5
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    SIZE_DIVISIBILITY: 24
    TEST:
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      WINDOW_INFERENCE: True
      WINDOW_SIZE: 3
      TASK: 'vis'
      MAX_NUM: 20
  RFDETR:
    ENCODER: "dinov2_windowed_small"
    OUT_FEATURE_INDEXES: [3, 6, 9, 12]
    PROJECTOR_SCALE: ["P4"]
    PATCH_SIZE: 12
    NUM_WINDOWS: 2
    POSITIONAL_ENCODING_SIZE: 42
    RESOLUTION: 504
    FREEZE_ENCODER: True
    HIDDEN_DIM: 256
    NUM_QUERIES: 300
    DEC_LAYERS: 5
    SA_NHEADS: 8
    CA_NHEADS: 16
    DEC_N_POINTS: 2
    DIM_FEEDFORWARD: 2048
    TWO_STAGE: True
    GROUP_DETR: 13
    BBOX_REPARAM: True
    LITE_REFPOINT_REFINE: True
    MASK_DOWNSAMPLE_RATIO: 4
    PRETRAIN_WEIGHTS: "/home/li.yu/code/mymnt/DVIS/pretrained_models/rf-detr-seg-large.pt"
  WEIGHTS: ""
  TRACKER:
    DECODER_LAYERS: 6
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
  IMS_PER_BATCH: 16 # for 1 GPU
  BASE_LR: 0.0001
  STEPS: (28000,)
  MAX_ITER: 40000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05

INPUT:
  MIN_SIZE_TRAIN: (360, 480, 504)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 480
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  SAMPLING_FRAME_SHUFFLE: False
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  CROP:
    ENABLED: False
    TYPE: "absolute_range"
    SIZE: (384, 600)
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (360, 480, 504)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: False
      TYPE: "absolute_range"
      SIZE: (384, 600)

DATASETS:
  DATASET_NEED_MAP: [False, ]
  DATASET_TYPE: ['video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  DATASET_RATIO: [1.0]
  TRAIN: ("ytvis_2022_train",)
  TEST: ("ytvis_2022_val",)

OUTPUT_DIR: './output_DVIS_Online_RFDETR_YTVIS22'
